version: '2'
services:
  jade-app:
    image: jade
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jade-mysql:3306/jade?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://jade-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jade-elasticsearch:9200
    ports:
      - 8080:8080
  jade-mysql:
    extends:
      file: mysql.yml
      service: jade-mysql
  jade-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jade-elasticsearch
